In [ ]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

print(my_arr)


[     0      1      2 ... 999997 999998 999999]


In [9]:
print(my_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [7]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 57 ms


In [8]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 1.4 s


In [10]:
# 基于Numpy的算法要比纯python快10到100倍，甚至更快，并且使用的内存更少

In [11]:
# 1.1 Numpy的ndarray:一种多维数组对象
"""
NumPy最重要的一个特点就是其N维数组对象（即ndarray），
该对象是一个快速而灵活的大数据集容器。
你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样。
"""

In [13]:
import numpy as np

# 生成一些随机数
data = np.random.randn(2, 3)  # 两行三列的随机数
print(data)

[[ 0.09489035 -1.46822839 -0.5041579 ]
 [-0.1853204   0.27162688 -1.52268768]]


In [15]:
# 所有元素都乘以10
print("data * 10：\n" , data * 10)

data * 10：
 [[  0.94890352 -14.68228385  -5.041579  ]
 [ -1.85320398   2.71626877 -15.22687684]]


In [16]:
# 每个元素与自身相加
print("data + data : \n", data + data)

data + data : 
 [[ 0.1897807  -2.93645677 -1.0083158 ]
 [-0.3706408   0.54325375 -3.04537537]]


In [18]:
"""
ndarray所有元素必须是相同类型的。
每个数组都有一个shape（一个表示各维度大小的元组）和
一个dtype（一个用于说明数组数据类型的对象）
"""
print("data shape: ", data.shape)
print("data dtype: ", data.dtype)

data shape:  (2, 3)
data dtype:  float64


## 创建数组

创建数组最简单的办法就是使用array函数。

In [20]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组：

In [21]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
# data2是列表的列表，NumPy数组arr2的两个维度的shape是从data2引入的
print(arr2.ndim)  # 维度
print(arr2.shape)  # 形状

2
(2, 4)


由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64（浮点数）

In [25]:
# 除非特别说明（稍后将会详细介绍），
# np.array会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的dtype对象中
print(arr1.dtype)
print(arr2.dtype)

float64
int32


除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [26]:
print(np.zeros(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.88081642e-312 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 3.79215188e+179]]

 [[3.69784746e-057 1.46202503e+185]
  [7.71801654e-043 2.95702945e-032]
  [1.73323759e+185 2.10682846e-076]]]


注意：认为np.empty会返回全0数组的想法是不安全的。很多情况下（如前所示），它返回的都是一些未初始化的垃圾值。

arange是Python内置函数range的数组版：

In [27]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## ndarray的数据类型

dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息：

In [28]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


可以通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype：

In [29]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


如果将浮点数转换成整数，则小数部分将会被截取删除：

In [30]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式：

In [31]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


注意：使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

数组的dtype还有另一个属性：

In [33]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


还可以用简洁的类型代码来表示dtype

In [35]:
empty_uint32 = np.empty(8, dtype='u4')
print(empty_uint32)
print(empty_uint32.dtype)

[         0 1075314688          0 1075707904          0 1075838976
          0 1072693248]
uint32


## 数组运算

In [36]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


数组与标量的算术运算会将标量值传播到各个元素：

In [37]:
print(1/arr)
print(arr ** 0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


大小相同的数组之间的比较会生成布尔值数组：

In [38]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


## 数组的广播

如果两个数组的维数不相同，则元素到元素的操作是不可能的。 然而，在 NumPy 中仍然可以对形状不相似的数组进行操作，因为它拥有广播功能。 较小的数组会广播到较大数组的大小，以便使它们的形状可兼容。

如果满足以下规则，可以进行广播：
- ndim较小的数组会在前面追加一个长度为 1 的维度。
- 输出数组的每个维度的大小是输入数组该维度大小的最大值。
- 如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则可以在计算中使用该输入。
- 如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。

如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。
- 数组拥有相同形状。
- 数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。
- 数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。

下面的例称展示了广播的示例。

In [39]:
import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print("第一个数组：")
print(a)
print("第二个数组：")
print(b)
print("第一个数组+第二个数组：")
print(a+b)

第一个数组：
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
第二个数组：
[1. 2. 3.]
第一个数组+第二个数组：
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## 基本的索引和切片

NumPy数组的索引是一个内容丰富的主题，因为选取数据子集或单个元素的方式有很多。一维数组很简单。从表面上看，它们跟Python列表的功能差不多：

In [40]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


如上所示，当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

创建一个arr的切片：

In [41]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


当我修稿arr_slice中的值，变动也会体现在原始数组arr中：

In [42]:
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


切片[ : ]会给数组中的所有值赋值：

In [43]:
arr_slice[:] = 64
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


注意：如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()

在一个二维数组中，各索引位置上的元素不再是标量而是一维数组

In [44]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])

[7 8 9]


可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的：

In [45]:
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）。因此，在2×2×3数组arr3d中：

In [2]:
import numpy as np
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


## 布尔型索引

In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.04515796  0.29033788 -1.06139435 -0.011779  ]
 [ 0.63222472 -0.35586659  0.20261125  0.23086065]
 [ 1.13244416 -1.60233684 -0.18147226  1.84759497]
 [ 0.40951329 -1.44302978 -0.93075433 -0.47311814]
 [ 1.05708108 -0.32333157  0.78881468  0.68265089]
 [-0.91033033 -0.94575219 -1.71840962  1.04611082]
 [-0.08326601 -1.04813864  0.43328329  1.01901384]]


假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算将会产生一个布尔型数组：

In [5]:
print(names == 'Bob')

[ True False False  True False False False]


这个布尔型数组可用于数组索引:

In [6]:
print(data[names=='Bob'])

[[-0.04515796  0.29033788 -1.06139435 -0.011779  ]
 [ 0.40951329 -1.44302978 -0.93075433 -0.47311814]]


布尔型数组的长度必须跟被索引的轴长度一致。此外，还可以将布尔型数组跟切片、整数（或整数序列，稍后将对此进行详细讲解）混合使用：

下面的例子，我选取了names == 'Bob'的行，并索引了列：

In [8]:
print(data[names=='Bob', 2:])
print("++++++++++++++++++++++++")
print(data[names=='Bob', 3])

[[-1.06139435 -0.011779  ]
 [-0.93075433 -0.47311814]]
++++++++++++++++++++++++
[-0.011779   -0.47311814]


要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定：

In [9]:
print(names != 'Bob')
print("++++++++++++++++++++")
print(data[~(names == 'Bob')])

[False  True  True False  True  True  True]
++++++++++++++++++++
[[ 0.63222472 -0.35586659  0.20261125  0.23086065]
 [ 1.13244416 -1.60233684 -0.18147226  1.84759497]
 [ 1.05708108 -0.32333157  0.78881468  0.68265089]
 [-0.91033033 -0.94575219 -1.71840962  1.04611082]
 [-0.08326601 -1.04813864  0.43328329  1.01901384]]


~操作符用来反转条件很好用：

In [10]:
cond = names == 'Bob'
print(data[~cond])

[[ 0.63222472 -0.35586659  0.20261125  0.23086065]
 [ 1.13244416 -1.60233684 -0.18147226  1.84759497]
 [ 1.05708108 -0.32333157  0.78881468  0.68265089]
 [-0.91033033 -0.94575219 -1.71840962  1.04611082]
 [-0.08326601 -1.04813864  0.43328329  1.01901384]]


选取这三个名字中的两个需要组合应用多个布尔条件，使用&（和）、|（或）之类的布尔算术运算符即可：

In [11]:
mask = (names=='Bob')|(names=='Will')
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[-0.04515796  0.29033788 -1.06139435 -0.011779  ]
 [ 1.13244416 -1.60233684 -0.18147226  1.84759497]
 [ 0.40951329 -1.44302978 -0.93075433 -0.47311814]
 [ 1.05708108 -0.32333157  0.78881468  0.68265089]]


通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此。

注意：Python关键字and和or在布尔型数组中无效。要使用&与|。

通过布尔型数组设置值是一种经常用到的手段。为了将data中的所有负值都设置为0，我们只需：

In [12]:
data[data<0] = 0
print(data)

[[0.         0.29033788 0.         0.        ]
 [0.63222472 0.         0.20261125 0.23086065]
 [1.13244416 0.         0.         1.84759497]
 [0.40951329 0.         0.         0.        ]
 [1.05708108 0.         0.78881468 0.68265089]
 [0.         0.         0.         1.04611082]
 [0.         0.         0.43328329 1.01901384]]


通过一维布尔数组设置整行或列的值也很简单：

In [13]:
data[names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.63222472 0.         0.20261125 0.23086065]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.         0.         1.04611082]
 [0.         0.         0.43328329 1.01901384]]


## 花式索引

花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。假设我们有一个8×4数组：

In [18]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可：

In [19]:
print(arr[[4, 3, 0, 6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


这段代码确实达到我们的要求了！使用负数索引将会从末尾开始选取行：

In [20]:
print(arr[[-3, -5, -7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：

In [21]:
arr = np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [22]:
print(arr[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]
